### ISSUE TITLE
Add Login Page

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#1]
I need simple login page in my Flutter Apps

**Comment by WaAlvis** [comment]
I would like to work on this, as my first open source contribution!!

**Comment by erikrios** [comment]
@WaAlvis This is the layout

<img src="https://user-images.githubusercontent.com/42199285/95114322-f3ea9980-076d-11eb-925d-57129dcf1cb6.png" width="360" height="640">

**Comment by WaAlvis** [comment]
create login_page, Will Alvis #2

**Comment by WaAlvis** [comment]
Is there any way you can help me to tell me about my contribution to HacktoberFest?
appears with this label

![image](https://user-images.githubusercontent.com/41210700/95156316-e0363780-075b-11eb-8517-d627a66d96e9.png)

**Comment by WaAlvis** [comment]
so it will help in my application, you want to add **hacktoberfest** topic to the repo in order to participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by erikrios** [comment]
![image](https://user-images.githubusercontent.com/42199285/95158554-15776f80-07c6-11eb-88ee-a03257dd7102.png)

Hi @WaAlvis , thanks for contributing to my repo. I already add the "hacktoberfest" topic to my repository"
