### ISSUE TITLE
Add tl-PH Filipino (Philippines) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#11]
I need to translate my app in tl-PH Filipino (Philippines). You can contribute by following this step:

-   [ ] Go to assets/translations folder

-   [ ] Create tl-PH.json file

-   [ ] Translate en.json to tl-PH.json

-   [ ] Create a pull request

-   [ ] I will merged it

**Comment by astrayama** [comment]
Hey there 👋🏼 I'd like to work on this issue! Can you assign it to me, @erikrios?
