### ISSUE TITLE
Add vi-VN Vietnamese (Vietnam) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#13]
I need to translate my app in vi-VN Vietnamese (Vietnam). You can contribute by following this step:

-   [x] Go to assets/translations folder

-   [x] Create vi-VN.json file

-   [x] Translate en.json to vi-VN.json

-   [x] Create a pull request

-   [ ] I will merged it

**Comment by ywalia01** [comment]
Hey, I'd like to work on this
