### ISSUE TITLE
Add af-ZA Afrikaans (South Africa) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#18]
I need to translate my app in af-ZA Afrikaans (South Africa). You can contribute by following this step:

-   [ ] Go to assets/translations folder

-   [ ] Create af-ZA.json file

-   [ ] Translate en.json to af-ZA.json

-   [ ] Create a pull request

-   [ ] I will merged it

**Comment by Halix267** [comment]
Hey Can i work on this

**Comment by erikrios** [comment]
@Halix267  Yes, sure
