### ISSUE TITLE
Add pt-PT Portuguese (Portugal) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#19]
I need to translate my app in pt-PT Portuguese (Portugal). You can contribute by following this step:

-   [ ] Go to assets/translations folder

-   [ ] Create pt-PT.json file

-   [ ] Translate en.json to pt-PT.json

-   [ ] Create a pull request

-   [ ] I will merged it

**Comment by M4yankChoudhary** [comment]
Can i take this ?

**Comment by erikrios** [comment]
@M4yankChoudhary Yes, sure
