### ISSUE TITLE
Add fr-FR French (France) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#20]
I need to translate my app in fr-FR French (France). You can contribute by following this step:

-   [ ] Go to assets/translations folder

-   [ ] Create fr-FR.json file

-   [ ] Translate en.json to fr-FR.json

-   [ ] Create a pull request

-   [ ] I will merged it

**Comment by Vrindagupta6828** [comment]
@erikrios hey can i work on this?

**Comment by Vrindagupta6828** [comment]
I have added it please review and merge it. #29
