### ISSUE TITLE
Add bn-IN Bengali (India) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#21]
I need to translate my app in bn-IN Bengali (India). You can contribute by following this step:

-   [ ] Go to assets/translations folder

-   [ ] Create bn-IN.json file

-   [ ] Translate en.json to bn-IN.json

-   [ ] Create a pull request

-   [ ] I will merged it

**Comment by anshcena** [comment]
(bn-IN.json and translation : added) [#25](https://github.com/erikrios/reog-apps-flutter/pull/25)
