### ISSUE TITLE
Add hi-IN Hindi (India) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#3]
I need to translate my app in hi-IN Hindi (India). You can contribute by following this step:

-   [x] Go to assets/translations folder

-   [x] Create hi-IN.json file

-   [x] Translate en.json to hi-IN.json

-   [x] Create a pull request

-   [x] I will merged it

**Comment by vipinagrahari** [comment]
Added a PR for this. https://github.com/erikrios/reog-apps-flutter/pull/9

**Comment by erikrios** [comment]
Thanks for your contribution @vipinagrahari
