### ISSUE TITLE
Add ms-MY Malay (Malaysia) Translation

### ISSUE THREAD

**Issue by erikrios** [erikrios/reog-apps-flutter#5]
I need to translate my app in ms-MY Malay (Malaysia). You can contribute by following this step:

-   [ ] Go to assets/translations folder

-   [ ] Create ms-MY.json file

-   [ ] Translate en.json to ms-MY.json

-   [ ] Create a pull request

-   [ ] I will merged it

**Comment by JanitChawla** [comment]
I would like to do this can u assign me this issue.

**Comment by erikrios** [comment]
@JanitChawla Yes, sure

**Comment by JanitChawla** [comment]
@erikrios please check my pull request
